### ISSUE TITLE
Quotation marks in toc file titles

### ISSUE THREAD

**Issue by ddundo** [primer-computational-mathematics/book#3]
There is an issue when there are quotation marks in notebook titles, now taken from the first header in the file. I tried replacing " or ' with \\" or \\' in generate_toc script but it still didn't work.

I warned others not to use " in the first header for now but it would be good to have this working I think

**Comment by jrper** [comment]
Escaping characters is always painful. In this case it's an awkward interaction between python and yaml.

After a ltitle bit of experimentation, I believe the fix is to have
`title =  title.group().split("#")[-1].strip().replace('"', r'\"')`
in line 22 of `generate_new_toc.py`, where the `r''` allows us to give a raw, unescaped string (alternatively, we could use `\\"`

Would you mind checking if that fixes your problem? If it works and doesn't break anything else, feel free to make the change.

**Comment by ddundo** [comment]
Thanks James - that does seem to work! I didn't put the `r''` before :)
